package com.recruitment.recruitmentsystem.model;

public enum FieldOfStudy {
    AERONAUTICS_AND_AVIATION_SIENCE,
    ANTHROPOLOGY,
    ART,
    BUISNESS_ADMINISTRATION,
    CHEMISTRY,
    ECONOMICS,
    EDUCATION,
    ENGINEERING,
    ENVIROMENTAL_SCIENCE_AND_HEALTH,
    JOURNALISM_AND_MASS_COMMUNICATION,
    MUSIC,
    NURSING,
    OCEANOGRAPHY,
    PHARMACY,
    PHOTOGRAPHY,
    PHISICAL_THERAPY,
    PSYCHOLOGY,
    PUBLIC_RELATION_AND_ADMINISTRATION,
    STATISTIC,
    URBAN_PLANNING;
}
